//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TipsiSyncCSharpClient.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Address : global::System.Configuration.ApplicationSettingsBase {
        
        private static Address defaultInstance = ((Address)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Address())));
        
        public static Address Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://test.gettipsi.com/")]
        public string DomainURL {
            get {
                return ((string)(this["DomainURL"]));
            }
            set {
                this["DomainURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("api/rest/v001/login")]
        public string LoginURL {
            get {
                return ((string)(this["LoginURL"]));
            }
            set {
                this["LoginURL"] = value;
            }
        }
    }
}
